<?php

/**
 * Implements hook_theme().
 */
function block_component_theme($existing, $type, $theme, $path): array
{
  return [
    'hello_block' => [
      'variables' => [
        'text' => NULL,
      ],
    ],
    'custom_carousel' => [
      'variables' => [
        'images' => []
      ]
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function block_component_preprocess_block(&$variables)
{
  if ($variables['plugin_id'] == 'custom_carousel_block') {
    $variables['#attached']['library'][] = 'block_component/bootstrap-carousel';
  }
}
